### REGISTER AND LOGIN ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "admin123"
}


### Get all products
GET http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYmVsdHJhbm9AbWFpbC5jb20iLCJpYXQiOjE3NDg4NzE4ODgsImV4cCI6MTc0ODg3NTQ4OH0.OQQoSgEqqjfB_KQnV96yFWRq3J1CD1MflKIuYdZRFZg

### Get product by ID
GET http://localhost:3000/product/search?title=shirt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiY2VjaWxpYUBtYWlsLmNvbSIsImlhdCI6MTc0ODY0MDExMywiZXhwIjoxNzQ4NjQwMTczfQ.RwMfyFkkR3RmM-wVEI4p7EtV-KWK_AOA4iWQLl4gLz4

### Get product by ID
GET http://localhost:3000/product/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYmVsdHJhbm9AbWFpbC5jb20iLCJpYXQiOjE3NDg4NzE4ODgsImV4cCI6MTc0ODg3NTQ4OH0.OQQoSgEqqjfB_KQnV96yFWRq3J1CD1MflKIuYdZRFZg


### CART
GET http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYmVsdHJhbm9AbWFpbC5jb20iLCJpYXQiOjE3NDg4NzE4ODgsImV4cCI6MTc0ODg3NTQ4OH0.OQQoSgEqqjfB_KQnV96yFWRq3J1CD1MflKIuYdZRFZg

### Add to cart
POST http://localhost:3000/cart/add/19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYmVsdHJhbm9AbWFpbC5jb20iLCJpYXQiOjE3NDg4NzE4ODgsImV4cCI6MTc0ODg3NTQ4OH0.OQQoSgEqqjfB_KQnV96yFWRq3J1CD1MflKIuYdZRFZg


### Remove from cart
DELETE http://localhost:3000/cart/remove/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYmVsdHJhbm9AbWFpbC5jb20iLCJpYXQiOjE3NDg4NzE4ODgsImV4cCI6MTc0ODg3NTQ4OH0.OQQoSgEqqjfB_KQnV96yFWRq3J1CD1MflKIuYdZRFZg

