### Get all products
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "ciclano",
    "email": "ciclano@mail.com",
    "password": "123456"
}

###
### Get product by ID
POST http://localhost:3000/product/import
Content-Type: application/json



###
### Create new product
POST http://localhost:3000
Content-Type: application/json

{
    "name": "Produto Teste",
    "price": 29.99,
    "description": "Descrição do produto teste"
}

###
### Update product
PATCH http://localhost:3000/
Content-Type: application/json

{
    "name": "Produto Atualizado",
    "price": 39.99
}

###
### Delete product
DELETE http://localhost:3000/
Content-Type: application/json
