### Get all products

### Get product by ID
POST http://localhost:3000/product/import
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiY2VjaWxpYUBtYWlsLmNvbSIsImlhdCI6MTc0ODY0MDExMywiZXhwIjoxNzQ4NjQwMTczfQ.RwMfyFkkR3RmM-wVEI4p7EtV-KWK_AOA4iWQLl4gLz4



###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "cecilia@mail.com",
    "password": "123456"
}

### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "cecilia",
    "email": "cecilia@mail.com",
    "password": "123456"
}


### Create new product
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiY2VjaWxpYUBtYWlsLmNvbSIsImlhdCI6MTc0ODY0MDAzNywiZXhwIjoxNzQ4NjQwMDk3fQ.o_AgSTT9tHw4_nGYVvM8Ei_f4hzT_sshcScAZpN-MkM


### CART
GET http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiY2VjaWxpYUBtYWlsLmNvbSIsImlhdCI6MTc0ODY0NjcwMiwiZXhwIjoxNzQ4NjUwMzAyfQ.OkucEcuJ-PsfTDt-PeI8fxwDBI01Bkf-Ijww6eA8vxM

### Add to cart
POST http://localhost:3000/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiY2VjaWxpYUBtYWlsLmNvbSIsImlhdCI6MTc0ODY0NjcwMiwiZXhwIjoxNzQ4NjUwMzAyfQ.OkucEcuJ-PsfTDt-PeI8fxwDBI01Bkf-Ijww6eA8vxM

{
    "productId": 1
}